server:
  port: 22000
  servlet:
    context-path: "/stitch-crawler"

spring:
  application:
    name: crawler-server


grpc:
  server:
    port: 60051
    maxInboundMessageSize: 20971520


logging:
  level:
    io.grpc.netty: INFO
    org.eclipse.jetty: INFO
    org.springframework.web: INFO
    com.newsbreak: INFO


fetch:
  userAgents:
    - "Mozilla/5.0 (compatible; Bingbot/2.0; +http://www.bing.com/bingbot.htm)"
    - "Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)"
    - "DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)"
    - "Mozilla/5.0 (compatible; Konqueror/3.5; Linux) KHTML/3.5.5 (like Gecko) (Exabot-Thumbnails)"
    - "ia_archiver (+http://www.alexa.com/site/help/webmasters; crawler@alexa.com)"
  timeout : 180
  proxyActive: true
  tlsTrustAllCerts: true
  dynamicCipherSuites: false
  cipherSuites:
    - "TLS_AES_128_GCM_SHA256"
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_DHE_DSS_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256"
    - "TLS_DHE_DSS_WITH_AES_128_GCM_SHA256"
    - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
    - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384"
    - "TLS_RSA_WITH_AES_256_CBC_SHA256"
    - "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384"
    - "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384"
    - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA256"
    - "TLS_DHE_DSS_WITH_AES_256_CBC_SHA256"
    - "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA"
    - "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
    - "TLS_RSA_WITH_AES_256_CBC_SHA"
    - "TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA"
    - "TLS_ECDH_RSA_WITH_AES_256_CBC_SHA"
    - "TLS_DHE_RSA_WITH_AES_256_CBC_SHA"
    - "TLS_DHE_DSS_WITH_AES_256_CBC_SHA"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256"
    - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
    - "TLS_RSA_WITH_AES_128_CBC_SHA256"
    - "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256"
    - "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256"
    - "TLS_DHE_RSA_WITH_AES_128_CBC_SHA256"
    - "TLS_DHE_DSS_WITH_AES_128_CBC_SHA256"
    - "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA"
    - "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"
    - "TLS_RSA_WITH_AES_128_CBC_SHA"
    - "TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA"
    - "TLS_ECDH_RSA_WITH_AES_128_CBC_SHA"
    - "TLS_DHE_RSA_WITH_AES_128_CBC_SHA"
    - "TLS_DHE_DSS_WITH_AES_128_CBC_SHA"
    - "TLS_EMPTY_RENEGOTIATION_INFO_SCSV"
  proxies:
    - 127.0.0.1:1087
