// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.protobuf;

public interface FetchResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fetch.FetchResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string real_url = 1;</code>
   */
  String getRealUrl();
  /**
   * <code>string real_url = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealUrlBytes();

  /**
   * <code>int32 http_code = 2;</code>
   */
  int getHttpCode();

  /**
   * <code>string http_msg = 3;</code>
   */
  String getHttpMsg();
  /**
   * <code>string http_msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getHttpMsgBytes();

  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */
  int getHeaderCount();
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */
  boolean containsHeader(
          String key);
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Strings>
  getHeader();
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */
  java.util.Map<String, Strings>
  getHeaderMap();
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */

  Strings getHeaderOrDefault(
          String key,
          Strings defaultValue);
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */

  Strings getHeaderOrThrow(
          String key);

  /**
   * <code>string proto = 5;</code>
   */
  String getProto();
  /**
   * <code>string proto = 5;</code>
   */
  com.google.protobuf.ByteString
      getProtoBytes();

  /**
   * <code>bytes body = 6;</code>
   */
  com.google.protobuf.ByteString getBody();

  /**
   * <code>int64 fetch_cost = 7;</code>
   */
  long getFetchCost();

  /**
   * <code>int64 ts = 8;</code>
   */
  long getTs();
}
