// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.protobuf;

public interface FetchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fetch.FetchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   */
  String getUrl();
  /**
   * <code>string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string proxy = 2;</code>
   */
  String getProxy();
  /**
   * <code>string proxy = 2;</code>
   */
  com.google.protobuf.ByteString
      getProxyBytes();

  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 3;</code>
   */
  int getHeaderCount();
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 3;</code>
   */
  boolean containsHeader(
          String key);
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Strings>
  getHeader();
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 3;</code>
   */
  java.util.Map<String, Strings>
  getHeaderMap();
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 3;</code>
   */

  Strings getHeaderOrDefault(
          String key,
          Strings defaultValue);
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 3;</code>
   */

  Strings getHeaderOrThrow(
          String key);
}
