// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.protobuf;

/**
 * Protobuf type {@code fetch.FetchResponse}
 */
public  final class FetchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:fetch.FetchResponse)
        FetchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchResponse.newBuilder() to construct.
  private FetchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchResponse() {
    realUrl_ = "";
    httpMsg_ = "";
    proto_ = "";
    body_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FetchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            realUrl_ = s;
            break;
          }
          case 16: {

            httpCode_ = input.readInt32();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            httpMsg_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              header_ = com.google.protobuf.MapField.newMapField(
                  HeaderDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<String, Strings>
            header__ = input.readMessage(
                HeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            header_.getMutableMap().put(
                header__.getKey(), header__.getValue());
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            proto_ = s;
            break;
          }
          case 50: {

            body_ = input.readBytes();
            break;
          }
          case 56: {

            fetchCost_ = input.readInt64();
            break;
          }
          case 64: {

            ts_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FetchProto.internal_static_fetch_FetchResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetHeader();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FetchProto.internal_static_fetch_FetchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            FetchResponse.class, FetchResponse.Builder.class);
  }

  private int bitField0_;
  public static final int REAL_URL_FIELD_NUMBER = 1;
  private volatile Object realUrl_;
  /**
   * <code>string real_url = 1;</code>
   */
  public String getRealUrl() {
    Object ref = realUrl_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      realUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string real_url = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRealUrlBytes() {
    Object ref = realUrl_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      realUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HTTP_CODE_FIELD_NUMBER = 2;
  private int httpCode_;
  /**
   * <code>int32 http_code = 2;</code>
   */
  public int getHttpCode() {
    return httpCode_;
  }

  public static final int HTTP_MSG_FIELD_NUMBER = 3;
  private volatile Object httpMsg_;
  /**
   * <code>string http_msg = 3;</code>
   */
  public String getHttpMsg() {
    Object ref = httpMsg_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      httpMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string http_msg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getHttpMsgBytes() {
    Object ref = httpMsg_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      httpMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADER_FIELD_NUMBER = 4;
  private static final class HeaderDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        String, Strings> defaultEntry =
            com.google.protobuf.MapEntry
            .<String, Strings>newDefaultInstance(
                FetchProto.internal_static_fetch_FetchResponse_HeaderEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                Strings.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      String, Strings> header_;
  private com.google.protobuf.MapField<String, Strings>
  internalGetHeader() {
    if (header_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          HeaderDefaultEntryHolder.defaultEntry);
    }
    return header_;
  }

  public int getHeaderCount() {
    return internalGetHeader().getMap().size();
  }
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */

  public boolean containsHeader(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetHeader().getMap().containsKey(key);
  }
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, Strings> getHeader() {
    return getHeaderMap();
  }
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */

  public java.util.Map<String, Strings> getHeaderMap() {
    return internalGetHeader().getMap();
  }
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */

  public Strings getHeaderOrDefault(
      String key,
      Strings defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, Strings> map =
        internalGetHeader().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
   */

  public Strings getHeaderOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, Strings> map =
        internalGetHeader().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PROTO_FIELD_NUMBER = 5;
  private volatile Object proto_;
  /**
   * <code>string proto = 5;</code>
   */
  public String getProto() {
    Object ref = proto_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      proto_ = s;
      return s;
    }
  }
  /**
   * <code>string proto = 5;</code>
   */
  public com.google.protobuf.ByteString
      getProtoBytes() {
    Object ref = proto_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      proto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString body_;
  /**
   * <code>bytes body = 6;</code>
   */
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  public static final int FETCH_COST_FIELD_NUMBER = 7;
  private long fetchCost_;
  /**
   * <code>int64 fetch_cost = 7;</code>
   */
  public long getFetchCost() {
    return fetchCost_;
  }

  public static final int TS_FIELD_NUMBER = 8;
  private long ts_;
  /**
   * <code>int64 ts = 8;</code>
   */
  public long getTs() {
    return ts_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRealUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, realUrl_);
    }
    if (httpCode_ != 0) {
      output.writeInt32(2, httpCode_);
    }
    if (!getHttpMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, httpMsg_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetHeader(),
        HeaderDefaultEntryHolder.defaultEntry,
        4);
    if (!getProtoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, proto_);
    }
    if (!body_.isEmpty()) {
      output.writeBytes(6, body_);
    }
    if (fetchCost_ != 0L) {
      output.writeInt64(7, fetchCost_);
    }
    if (ts_ != 0L) {
      output.writeInt64(8, ts_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRealUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, realUrl_);
    }
    if (httpCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, httpCode_);
    }
    if (!getHttpMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, httpMsg_);
    }
    for (java.util.Map.Entry<String, Strings> entry
         : internalGetHeader().getMap().entrySet()) {
      com.google.protobuf.MapEntry<String, Strings>
      header__ = HeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, header__);
    }
    if (!getProtoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, proto_);
    }
    if (!body_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, body_);
    }
    if (fetchCost_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, fetchCost_);
    }
    if (ts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, ts_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof FetchResponse)) {
      return super.equals(obj);
    }
    FetchResponse other = (FetchResponse) obj;

    if (!getRealUrl()
        .equals(other.getRealUrl())) return false;
    if (getHttpCode()
        != other.getHttpCode()) return false;
    if (!getHttpMsg()
        .equals(other.getHttpMsg())) return false;
    if (!internalGetHeader().equals(
        other.internalGetHeader())) return false;
    if (!getProto()
        .equals(other.getProto())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (getFetchCost()
        != other.getFetchCost()) return false;
    if (getTs()
        != other.getTs()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REAL_URL_FIELD_NUMBER;
    hash = (53 * hash) + getRealUrl().hashCode();
    hash = (37 * hash) + HTTP_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getHttpCode();
    hash = (37 * hash) + HTTP_MSG_FIELD_NUMBER;
    hash = (53 * hash) + getHttpMsg().hashCode();
    if (!internalGetHeader().getMap().isEmpty()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + internalGetHeader().hashCode();
    }
    hash = (37 * hash) + PROTO_FIELD_NUMBER;
    hash = (53 * hash) + getProto().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + FETCH_COST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFetchCost());
    hash = (37 * hash) + TS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTs());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static FetchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FetchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FetchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FetchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FetchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static FetchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static FetchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FetchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static FetchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static FetchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static FetchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static FetchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(FetchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code fetch.FetchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:fetch.FetchResponse)
          FetchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FetchProto.internal_static_fetch_FetchResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FetchProto.internal_static_fetch_FetchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FetchResponse.class, FetchResponse.Builder.class);
    }

    // Construct using com.newsbreak.fetch.protobuf.FetchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      realUrl_ = "";

      httpCode_ = 0;

      httpMsg_ = "";

      internalGetMutableHeader().clear();
      proto_ = "";

      body_ = com.google.protobuf.ByteString.EMPTY;

      fetchCost_ = 0L;

      ts_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FetchProto.internal_static_fetch_FetchResponse_descriptor;
    }

    @Override
    public FetchResponse getDefaultInstanceForType() {
      return FetchResponse.getDefaultInstance();
    }

    @Override
    public FetchResponse build() {
      FetchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public FetchResponse buildPartial() {
      FetchResponse result = new FetchResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.realUrl_ = realUrl_;
      result.httpCode_ = httpCode_;
      result.httpMsg_ = httpMsg_;
      result.header_ = internalGetHeader();
      result.header_.makeImmutable();
      result.proto_ = proto_;
      result.body_ = body_;
      result.fetchCost_ = fetchCost_;
      result.ts_ = ts_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof FetchResponse) {
        return mergeFrom((FetchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(FetchResponse other) {
      if (other == FetchResponse.getDefaultInstance()) return this;
      if (!other.getRealUrl().isEmpty()) {
        realUrl_ = other.realUrl_;
        onChanged();
      }
      if (other.getHttpCode() != 0) {
        setHttpCode(other.getHttpCode());
      }
      if (!other.getHttpMsg().isEmpty()) {
        httpMsg_ = other.httpMsg_;
        onChanged();
      }
      internalGetMutableHeader().mergeFrom(
          other.internalGetHeader());
      if (!other.getProto().isEmpty()) {
        proto_ = other.proto_;
        onChanged();
      }
      if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
        setBody(other.getBody());
      }
      if (other.getFetchCost() != 0L) {
        setFetchCost(other.getFetchCost());
      }
      if (other.getTs() != 0L) {
        setTs(other.getTs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      FetchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (FetchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object realUrl_ = "";
    /**
     * <code>string real_url = 1;</code>
     */
    public String getRealUrl() {
      Object ref = realUrl_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        realUrl_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRealUrlBytes() {
      Object ref = realUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        realUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public Builder setRealUrl(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      realUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public Builder clearRealUrl() {

      realUrl_ = getDefaultInstance().getRealUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public Builder setRealUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      realUrl_ = value;
      onChanged();
      return this;
    }

    private int httpCode_ ;
    /**
     * <code>int32 http_code = 2;</code>
     */
    public int getHttpCode() {
      return httpCode_;
    }
    /**
     * <code>int32 http_code = 2;</code>
     */
    public Builder setHttpCode(int value) {

      httpCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 http_code = 2;</code>
     */
    public Builder clearHttpCode() {

      httpCode_ = 0;
      onChanged();
      return this;
    }

    private Object httpMsg_ = "";
    /**
     * <code>string http_msg = 3;</code>
     */
    public String getHttpMsg() {
      Object ref = httpMsg_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        httpMsg_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHttpMsgBytes() {
      Object ref = httpMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        httpMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public Builder setHttpMsg(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      httpMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public Builder clearHttpMsg() {

      httpMsg_ = getDefaultInstance().getHttpMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public Builder setHttpMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      httpMsg_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        String, Strings> header_;
    private com.google.protobuf.MapField<String, Strings>
    internalGetHeader() {
      if (header_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      return header_;
    }
    private com.google.protobuf.MapField<String, Strings>
    internalGetMutableHeader() {
      onChanged();;
      if (header_ == null) {
        header_ = com.google.protobuf.MapField.newMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      if (!header_.isMutable()) {
        header_ = header_.copy();
      }
      return header_;
    }

    public int getHeaderCount() {
      return internalGetHeader().getMap().size();
    }
    /**
     * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
     */

    public boolean containsHeader(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetHeader().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, Strings> getHeader() {
      return getHeaderMap();
    }
    /**
     * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
     */

    public java.util.Map<String, Strings> getHeaderMap() {
      return internalGetHeader().getMap();
    }
    /**
     * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
     */

    public Strings getHeaderOrDefault(
        String key,
        Strings defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Strings> map =
          internalGetHeader().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
     */

    public Strings getHeaderOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, Strings> map =
          internalGetHeader().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearHeader() {
      internalGetMutableHeader().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
     */

    public Builder removeHeader(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      internalGetMutableHeader().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<String, Strings>
    getMutableHeader() {
      return internalGetMutableHeader().getMutableMap();
    }
    /**
     * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
     */
    public Builder putHeader(
        String key,
        Strings value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableHeader().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .fetch.Strings&gt; header = 4;</code>
     */

    public Builder putAllHeader(
        java.util.Map<String, Strings> values) {
      internalGetMutableHeader().getMutableMap()
          .putAll(values);
      return this;
    }

    private Object proto_ = "";
    /**
     * <code>string proto = 5;</code>
     */
    public String getProto() {
      Object ref = proto_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        proto_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string proto = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProtoBytes() {
      Object ref = proto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        proto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proto = 5;</code>
     */
    public Builder setProto(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      proto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proto = 5;</code>
     */
    public Builder clearProto() {

      proto_ = getDefaultInstance().getProto();
      onChanged();
      return this;
    }
    /**
     * <code>string proto = 5;</code>
     */
    public Builder setProtoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      proto_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes body = 6;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>bytes body = 6;</code>
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }

      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes body = 6;</code>
     */
    public Builder clearBody() {

      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }

    private long fetchCost_ ;
    /**
     * <code>int64 fetch_cost = 7;</code>
     */
    public long getFetchCost() {
      return fetchCost_;
    }
    /**
     * <code>int64 fetch_cost = 7;</code>
     */
    public Builder setFetchCost(long value) {

      fetchCost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 fetch_cost = 7;</code>
     */
    public Builder clearFetchCost() {

      fetchCost_ = 0L;
      onChanged();
      return this;
    }

    private long ts_ ;
    /**
     * <code>int64 ts = 8;</code>
     */
    public long getTs() {
      return ts_;
    }
    /**
     * <code>int64 ts = 8;</code>
     */
    public Builder setTs(long value) {

      ts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ts = 8;</code>
     */
    public Builder clearTs() {

      ts_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:fetch.FetchResponse)
  }

  // @@protoc_insertion_point(class_scope:fetch.FetchResponse)
  private static final FetchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new FetchResponse();
  }

  public static FetchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchResponse>() {
    @Override
    public FetchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<FetchResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public FetchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

