// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.protobuf;

public final class FetchProto {
  private FetchProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_Strings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_Strings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchRequest_HeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchRequest_HeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchResponse_HeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchResponse_HeaderEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013fetch.proto\022\005fetch\"\030\n\007Strings\022\r\n\005value" +
      "\030\001 \003(\t\"\232\001\n\014FetchRequest\022\013\n\003url\030\001 \001(\t\022\r\n\005" +
      "proxy\030\002 \001(\t\022/\n\006header\030\003 \003(\0132\037.fetch.Fetc" +
      "hRequest.HeaderEntry\032=\n\013HeaderEntry\022\013\n\003k" +
      "ey\030\001 \001(\t\022\035\n\005value\030\002 \001(\0132\016.fetch.Strings:" +
      "\0028\001\"\364\001\n\rFetchResponse\022\020\n\010real_url\030\001 \001(\t\022" +
      "\021\n\thttp_code\030\002 \001(\005\022\020\n\010http_msg\030\003 \001(\t\0220\n\006" +
      "header\030\004 \003(\0132 .fetch.FetchResponse.Heade" +
      "rEntry\022\r\n\005proto\030\005 \001(\t\022\014\n\004body\030\006 \001(\014\022\022\n\nf" +
      "etch_cost\030\007 \001(\003\022\n\n\002ts\030\010 \001(\003\032=\n\013HeaderEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\035\n\005value\030\002 \001(\0132\016.fetch.S" +
      "trings:\0028\0012D\n\014FetchService\0224\n\005Fetch\022\023.fe" +
      "tch.FetchRequest\032\024.fetch.FetchResponse\"\000" +
      "B,\n\034com.newsbreak.fetch.protobufB\nFetchP" +
      "rotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_fetch_Strings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fetch_Strings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_Strings_descriptor,
        new String[] { "Value", });
    internal_static_fetch_FetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fetch_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchRequest_descriptor,
        new String[] { "Url", "Proxy", "Header", });
    internal_static_fetch_FetchRequest_HeaderEntry_descriptor =
      internal_static_fetch_FetchRequest_descriptor.getNestedTypes().get(0);
    internal_static_fetch_FetchRequest_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchRequest_HeaderEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_fetch_FetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fetch_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchResponse_descriptor,
        new String[] { "RealUrl", "HttpCode", "HttpMsg", "Header", "Proto", "Body", "FetchCost", "Ts", });
    internal_static_fetch_FetchResponse_HeaderEntry_descriptor =
      internal_static_fetch_FetchResponse_descriptor.getNestedTypes().get(0);
    internal_static_fetch_FetchResponse_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchResponse_HeaderEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
