// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.protobuf;

public interface StringsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fetch.Strings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string value = 1;</code>
   */
  java.util.List<String>
      getValueList();
  /**
   * <code>repeated string value = 1;</code>
   */
  int getValueCount();
  /**
   * <code>repeated string value = 1;</code>
   */
  String getValue(int index);
  /**
   * <code>repeated string value = 1;</code>
   */
  com.google.protobuf.ByteString
      getValueBytes(int index);
}
