// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.grpc.protobuf;

public final class CrawlerProto {
  private CrawlerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crawler_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_FetchRequest_HeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crawler_FetchRequest_HeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_FetchStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crawler_FetchStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crawler_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_FetchResponse_HeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crawler_FetchResponse_HeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crawler_FetchResponses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crawler_FetchResponses_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013fetch.proto\022\007crawler\"\273\001\n\014FetchRequest\022" +
      "\013\n\003url\030\001 \001(\t\022\r\n\005proxy\030\002 \001(\t\0221\n\006header\030\003 " +
      "\003(\0132!.crawler.FetchRequest.HeaderEntry\022\014" +
      "\n\004body\030\004 \001(\014\022\016\n\006method\030\005 \001(\t\022\017\n\007timeout\030" +
      "\006 \001(\003\032-\n\013HeaderEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val" +
      "ue\030\002 \001(\t:\0028\001\"<\n\013FetchStatus\022 \n\004code\030\001 \001(" +
      "\0162\022.crawler.FetchCode\022\013\n\003msg\030\002 \001(\t\"\250\002\n\rF" +
      "etchResponse\022\020\n\010real_url\030\001 \001(\t\022\021\n\thttp_c" +
      "ode\030\002 \001(\005\022\020\n\010http_msg\030\003 \001(\t\0222\n\006header\030\004 " +
      "\003(\0132\".crawler.FetchResponse.HeaderEntry\022" +
      "\r\n\005proto\030\005 \001(\t\022\014\n\004body\030\006 \001(\014\022\014\n\004cost\030\007 \001" +
      "(\003\022\n\n\002ts\030\010 \001(\003\022$\n\006status\030\t \001(\0132\024.crawler" +
      ".FetchStatus\022\r\n\005proxy\030\n \001(\t\022\021\n\tfetch_url" +
      "\030\013 \001(\t\032-\n\013HeaderEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"@\n\016FetchResponses\022.\n\016fetch" +
      "Responses\030\001 \003(\0132\026.crawler.FetchResponse*" +
      "w\n\tFetchCode\022\r\n\tUNFETCHED\020\000\022\013\n\007SUCCESS\020\001" +
      "\022\014\n\010IO_ERROR\020\002\022\021\n\rFETCHED_ERROR\020\003\022\021\n\rTIM" +
      "EOUT_ERROR\020\004\022\032\n\026ILLEGAL_ARGUMENT_ERROR\020\005" +
      "2\317\001\n\016CrawlerService\0228\n\005Fetch\022\025.crawler.F" +
      "etchRequest\032\026.crawler.FetchResponse\"\000\022@\n" +
      "\nMultiFetch\022\025.crawler.FetchRequest\032\027.cra" +
      "wler.FetchResponses\"\000(\001\022A\n\nAsyncFetch\022\025." +
      "crawler.FetchRequest\032\026.crawler.FetchResp" +
      "onse\"\000(\0010\001B:\n(com.linling.stitch.crawler" +
      ".grpc.protobufB\014CrawlerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_crawler_FetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crawler_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crawler_FetchRequest_descriptor,
        new java.lang.String[] { "Url", "Proxy", "Header", "Body", "Method", "Timeout", });
    internal_static_crawler_FetchRequest_HeaderEntry_descriptor =
      internal_static_crawler_FetchRequest_descriptor.getNestedTypes().get(0);
    internal_static_crawler_FetchRequest_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crawler_FetchRequest_HeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_crawler_FetchStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_crawler_FetchStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crawler_FetchStatus_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_crawler_FetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_crawler_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crawler_FetchResponse_descriptor,
        new java.lang.String[] { "RealUrl", "HttpCode", "HttpMsg", "Header", "Proto", "Body", "Cost", "Ts", "Status", "Proxy", "FetchUrl", });
    internal_static_crawler_FetchResponse_HeaderEntry_descriptor =
      internal_static_crawler_FetchResponse_descriptor.getNestedTypes().get(0);
    internal_static_crawler_FetchResponse_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crawler_FetchResponse_HeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_crawler_FetchResponses_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_crawler_FetchResponses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crawler_FetchResponses_descriptor,
        new java.lang.String[] { "FetchResponses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
