// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.grpc.protobuf;

public interface FetchResponsesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crawler.FetchResponses)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  java.util.List<com.linling.stitch.crawler.grpc.protobuf.FetchResponse> 
      getFetchResponsesList();
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  com.linling.stitch.crawler.grpc.protobuf.FetchResponse getFetchResponses(int index);
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  int getFetchResponsesCount();
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  java.util.List<? extends com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder> 
      getFetchResponsesOrBuilderList();
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder getFetchResponsesOrBuilder(
      int index);
}
