// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.grpc.protobuf;

/**
 * Protobuf type {@code crawler.FetchResponse}
 */
public  final class FetchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crawler.FetchResponse)
    FetchResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchResponse.newBuilder() to construct.
  private FetchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchResponse() {
    realUrl_ = "";
    httpMsg_ = "";
    proto_ = "";
    body_ = com.google.protobuf.ByteString.EMPTY;
    proxy_ = "";
    fetchUrl_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FetchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            realUrl_ = s;
            break;
          }
          case 16: {

            httpCode_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            httpMsg_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000008) != 0)) {
              header_ = com.google.protobuf.MapField.newMapField(
                  HeaderDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000008;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            header__ = input.readMessage(
                HeaderDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            header_.getMutableMap().put(
                header__.getKey(), header__.getValue());
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            proto_ = s;
            break;
          }
          case 50: {

            body_ = input.readBytes();
            break;
          }
          case 56: {

            cost_ = input.readInt64();
            break;
          }
          case 64: {

            ts_ = input.readInt64();
            break;
          }
          case 74: {
            com.linling.stitch.crawler.grpc.protobuf.FetchStatus.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(com.linling.stitch.crawler.grpc.protobuf.FetchStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            proxy_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            fetchUrl_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 4:
        return internalGetHeader();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.linling.stitch.crawler.grpc.protobuf.FetchResponse.class, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder.class);
  }

  private int bitField0_;
  public static final int REAL_URL_FIELD_NUMBER = 1;
  private volatile java.lang.Object realUrl_;
  /**
   * <code>string real_url = 1;</code>
   */
  public java.lang.String getRealUrl() {
    java.lang.Object ref = realUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      realUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string real_url = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRealUrlBytes() {
    java.lang.Object ref = realUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      realUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HTTP_CODE_FIELD_NUMBER = 2;
  private int httpCode_;
  /**
   * <code>int32 http_code = 2;</code>
   */
  public int getHttpCode() {
    return httpCode_;
  }

  public static final int HTTP_MSG_FIELD_NUMBER = 3;
  private volatile java.lang.Object httpMsg_;
  /**
   * <code>string http_msg = 3;</code>
   */
  public java.lang.String getHttpMsg() {
    java.lang.Object ref = httpMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      httpMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string http_msg = 3;</code>
   */
  public com.google.protobuf.ByteString
      getHttpMsgBytes() {
    java.lang.Object ref = httpMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      httpMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADER_FIELD_NUMBER = 4;
  private static final class HeaderDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponse_HeaderEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> header_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetHeader() {
    if (header_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          HeaderDefaultEntryHolder.defaultEntry);
    }
    return header_;
  }

  public int getHeaderCount() {
    return internalGetHeader().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; header = 4;</code>
   */

  public boolean containsHeader(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetHeader().getMap().containsKey(key);
  }
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getHeader() {
    return getHeaderMap();
  }
  /**
   * <code>map&lt;string, string&gt; header = 4;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
    return internalGetHeader().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; header = 4;</code>
   */

  public java.lang.String getHeaderOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeader().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; header = 4;</code>
   */

  public java.lang.String getHeaderOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetHeader().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PROTO_FIELD_NUMBER = 5;
  private volatile java.lang.Object proto_;
  /**
   * <code>string proto = 5;</code>
   */
  public java.lang.String getProto() {
    java.lang.Object ref = proto_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proto_ = s;
      return s;
    }
  }
  /**
   * <code>string proto = 5;</code>
   */
  public com.google.protobuf.ByteString
      getProtoBytes() {
    java.lang.Object ref = proto_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString body_;
  /**
   * <code>bytes body = 6;</code>
   */
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  public static final int COST_FIELD_NUMBER = 7;
  private long cost_;
  /**
   * <code>int64 cost = 7;</code>
   */
  public long getCost() {
    return cost_;
  }

  public static final int TS_FIELD_NUMBER = 8;
  private long ts_;
  /**
   * <code>int64 ts = 8;</code>
   */
  public long getTs() {
    return ts_;
  }

  public static final int STATUS_FIELD_NUMBER = 9;
  private com.linling.stitch.crawler.grpc.protobuf.FetchStatus status_;
  /**
   * <code>.crawler.FetchStatus status = 9;</code>
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.crawler.FetchStatus status = 9;</code>
   */
  public com.linling.stitch.crawler.grpc.protobuf.FetchStatus getStatus() {
    return status_ == null ? com.linling.stitch.crawler.grpc.protobuf.FetchStatus.getDefaultInstance() : status_;
  }
  /**
   * <code>.crawler.FetchStatus status = 9;</code>
   */
  public com.linling.stitch.crawler.grpc.protobuf.FetchStatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int PROXY_FIELD_NUMBER = 10;
  private volatile java.lang.Object proxy_;
  /**
   * <code>string proxy = 10;</code>
   */
  public java.lang.String getProxy() {
    java.lang.Object ref = proxy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proxy_ = s;
      return s;
    }
  }
  /**
   * <code>string proxy = 10;</code>
   */
  public com.google.protobuf.ByteString
      getProxyBytes() {
    java.lang.Object ref = proxy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proxy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FETCH_URL_FIELD_NUMBER = 11;
  private volatile java.lang.Object fetchUrl_;
  /**
   * <code>string fetch_url = 11;</code>
   */
  public java.lang.String getFetchUrl() {
    java.lang.Object ref = fetchUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fetchUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string fetch_url = 11;</code>
   */
  public com.google.protobuf.ByteString
      getFetchUrlBytes() {
    java.lang.Object ref = fetchUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fetchUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRealUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, realUrl_);
    }
    if (httpCode_ != 0) {
      output.writeInt32(2, httpCode_);
    }
    if (!getHttpMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, httpMsg_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetHeader(),
        HeaderDefaultEntryHolder.defaultEntry,
        4);
    if (!getProtoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, proto_);
    }
    if (!body_.isEmpty()) {
      output.writeBytes(6, body_);
    }
    if (cost_ != 0L) {
      output.writeInt64(7, cost_);
    }
    if (ts_ != 0L) {
      output.writeInt64(8, ts_);
    }
    if (status_ != null) {
      output.writeMessage(9, getStatus());
    }
    if (!getProxyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, proxy_);
    }
    if (!getFetchUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, fetchUrl_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRealUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, realUrl_);
    }
    if (httpCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, httpCode_);
    }
    if (!getHttpMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, httpMsg_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetHeader().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      header__ = HeaderDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, header__);
    }
    if (!getProtoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, proto_);
    }
    if (!body_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, body_);
    }
    if (cost_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, cost_);
    }
    if (ts_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, ts_);
    }
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getStatus());
    }
    if (!getProxyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, proxy_);
    }
    if (!getFetchUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, fetchUrl_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.linling.stitch.crawler.grpc.protobuf.FetchResponse)) {
      return super.equals(obj);
    }
    com.linling.stitch.crawler.grpc.protobuf.FetchResponse other = (com.linling.stitch.crawler.grpc.protobuf.FetchResponse) obj;

    if (!getRealUrl()
        .equals(other.getRealUrl())) return false;
    if (getHttpCode()
        != other.getHttpCode()) return false;
    if (!getHttpMsg()
        .equals(other.getHttpMsg())) return false;
    if (!internalGetHeader().equals(
        other.internalGetHeader())) return false;
    if (!getProto()
        .equals(other.getProto())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (getCost()
        != other.getCost()) return false;
    if (getTs()
        != other.getTs()) return false;
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (!getProxy()
        .equals(other.getProxy())) return false;
    if (!getFetchUrl()
        .equals(other.getFetchUrl())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REAL_URL_FIELD_NUMBER;
    hash = (53 * hash) + getRealUrl().hashCode();
    hash = (37 * hash) + HTTP_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getHttpCode();
    hash = (37 * hash) + HTTP_MSG_FIELD_NUMBER;
    hash = (53 * hash) + getHttpMsg().hashCode();
    if (!internalGetHeader().getMap().isEmpty()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + internalGetHeader().hashCode();
    }
    hash = (37 * hash) + PROTO_FIELD_NUMBER;
    hash = (53 * hash) + getProto().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + COST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCost());
    hash = (37 * hash) + TS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTs());
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    hash = (37 * hash) + PROXY_FIELD_NUMBER;
    hash = (53 * hash) + getProxy().hashCode();
    hash = (37 * hash) + FETCH_URL_FIELD_NUMBER;
    hash = (53 * hash) + getFetchUrl().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.linling.stitch.crawler.grpc.protobuf.FetchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crawler.FetchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crawler.FetchResponse)
      com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableHeader();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linling.stitch.crawler.grpc.protobuf.FetchResponse.class, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder.class);
    }

    // Construct using com.linling.stitch.crawler.grpc.protobuf.FetchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      realUrl_ = "";

      httpCode_ = 0;

      httpMsg_ = "";

      internalGetMutableHeader().clear();
      proto_ = "";

      body_ = com.google.protobuf.ByteString.EMPTY;

      cost_ = 0L;

      ts_ = 0L;

      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      proxy_ = "";

      fetchUrl_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponse_descriptor;
    }

    @java.lang.Override
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponse getDefaultInstanceForType() {
      return com.linling.stitch.crawler.grpc.protobuf.FetchResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponse build() {
      com.linling.stitch.crawler.grpc.protobuf.FetchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponse buildPartial() {
      com.linling.stitch.crawler.grpc.protobuf.FetchResponse result = new com.linling.stitch.crawler.grpc.protobuf.FetchResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.realUrl_ = realUrl_;
      result.httpCode_ = httpCode_;
      result.httpMsg_ = httpMsg_;
      result.header_ = internalGetHeader();
      result.header_.makeImmutable();
      result.proto_ = proto_;
      result.body_ = body_;
      result.cost_ = cost_;
      result.ts_ = ts_;
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      result.proxy_ = proxy_;
      result.fetchUrl_ = fetchUrl_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.linling.stitch.crawler.grpc.protobuf.FetchResponse) {
        return mergeFrom((com.linling.stitch.crawler.grpc.protobuf.FetchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.linling.stitch.crawler.grpc.protobuf.FetchResponse other) {
      if (other == com.linling.stitch.crawler.grpc.protobuf.FetchResponse.getDefaultInstance()) return this;
      if (!other.getRealUrl().isEmpty()) {
        realUrl_ = other.realUrl_;
        onChanged();
      }
      if (other.getHttpCode() != 0) {
        setHttpCode(other.getHttpCode());
      }
      if (!other.getHttpMsg().isEmpty()) {
        httpMsg_ = other.httpMsg_;
        onChanged();
      }
      internalGetMutableHeader().mergeFrom(
          other.internalGetHeader());
      if (!other.getProto().isEmpty()) {
        proto_ = other.proto_;
        onChanged();
      }
      if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
        setBody(other.getBody());
      }
      if (other.getCost() != 0L) {
        setCost(other.getCost());
      }
      if (other.getTs() != 0L) {
        setTs(other.getTs());
      }
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (!other.getProxy().isEmpty()) {
        proxy_ = other.proxy_;
        onChanged();
      }
      if (!other.getFetchUrl().isEmpty()) {
        fetchUrl_ = other.fetchUrl_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.linling.stitch.crawler.grpc.protobuf.FetchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.linling.stitch.crawler.grpc.protobuf.FetchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object realUrl_ = "";
    /**
     * <code>string real_url = 1;</code>
     */
    public java.lang.String getRealUrl() {
      java.lang.Object ref = realUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        realUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRealUrlBytes() {
      java.lang.Object ref = realUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public Builder setRealUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      realUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public Builder clearRealUrl() {
      
      realUrl_ = getDefaultInstance().getRealUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string real_url = 1;</code>
     */
    public Builder setRealUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      realUrl_ = value;
      onChanged();
      return this;
    }

    private int httpCode_ ;
    /**
     * <code>int32 http_code = 2;</code>
     */
    public int getHttpCode() {
      return httpCode_;
    }
    /**
     * <code>int32 http_code = 2;</code>
     */
    public Builder setHttpCode(int value) {
      
      httpCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 http_code = 2;</code>
     */
    public Builder clearHttpCode() {
      
      httpCode_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object httpMsg_ = "";
    /**
     * <code>string http_msg = 3;</code>
     */
    public java.lang.String getHttpMsg() {
      java.lang.Object ref = httpMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHttpMsgBytes() {
      java.lang.Object ref = httpMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public Builder setHttpMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      httpMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public Builder clearHttpMsg() {
      
      httpMsg_ = getDefaultInstance().getHttpMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string http_msg = 3;</code>
     */
    public Builder setHttpMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      httpMsg_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> header_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHeader() {
      if (header_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      return header_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableHeader() {
      onChanged();;
      if (header_ == null) {
        header_ = com.google.protobuf.MapField.newMapField(
            HeaderDefaultEntryHolder.defaultEntry);
      }
      if (!header_.isMutable()) {
        header_ = header_.copy();
      }
      return header_;
    }

    public int getHeaderCount() {
      return internalGetHeader().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; header = 4;</code>
     */

    public boolean containsHeader(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetHeader().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeaderMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeader() {
      return getHeaderMap();
    }
    /**
     * <code>map&lt;string, string&gt; header = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getHeaderMap() {
      return internalGetHeader().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; header = 4;</code>
     */

    public java.lang.String getHeaderOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeader().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; header = 4;</code>
     */

    public java.lang.String getHeaderOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeader().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearHeader() {
      internalGetMutableHeader().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; header = 4;</code>
     */

    public Builder removeHeader(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableHeader().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableHeader() {
      return internalGetMutableHeader().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; header = 4;</code>
     */
    public Builder putHeader(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableHeader().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; header = 4;</code>
     */

    public Builder putAllHeader(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableHeader().getMutableMap()
          .putAll(values);
      return this;
    }

    private java.lang.Object proto_ = "";
    /**
     * <code>string proto = 5;</code>
     */
    public java.lang.String getProto() {
      java.lang.Object ref = proto_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proto_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proto = 5;</code>
     */
    public com.google.protobuf.ByteString
        getProtoBytes() {
      java.lang.Object ref = proto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proto = 5;</code>
     */
    public Builder setProto(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proto = 5;</code>
     */
    public Builder clearProto() {
      
      proto_ = getDefaultInstance().getProto();
      onChanged();
      return this;
    }
    /**
     * <code>string proto = 5;</code>
     */
    public Builder setProtoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      proto_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes body = 6;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>bytes body = 6;</code>
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes body = 6;</code>
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }

    private long cost_ ;
    /**
     * <code>int64 cost = 7;</code>
     */
    public long getCost() {
      return cost_;
    }
    /**
     * <code>int64 cost = 7;</code>
     */
    public Builder setCost(long value) {
      
      cost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cost = 7;</code>
     */
    public Builder clearCost() {
      
      cost_ = 0L;
      onChanged();
      return this;
    }

    private long ts_ ;
    /**
     * <code>int64 ts = 8;</code>
     */
    public long getTs() {
      return ts_;
    }
    /**
     * <code>int64 ts = 8;</code>
     */
    public Builder setTs(long value) {
      
      ts_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 ts = 8;</code>
     */
    public Builder clearTs() {
      
      ts_ = 0L;
      onChanged();
      return this;
    }

    private com.linling.stitch.crawler.grpc.protobuf.FetchStatus status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.linling.stitch.crawler.grpc.protobuf.FetchStatus, com.linling.stitch.crawler.grpc.protobuf.FetchStatus.Builder, com.linling.stitch.crawler.grpc.protobuf.FetchStatusOrBuilder> statusBuilder_;
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.linling.stitch.crawler.grpc.protobuf.FetchStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public Builder setStatus(com.linling.stitch.crawler.grpc.protobuf.FetchStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public Builder setStatus(
        com.linling.stitch.crawler.grpc.protobuf.FetchStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public Builder mergeStatus(com.linling.stitch.crawler.grpc.protobuf.FetchStatus value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            com.linling.stitch.crawler.grpc.protobuf.FetchStatus.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchStatus.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.linling.stitch.crawler.grpc.protobuf.FetchStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.crawler.FetchStatus status = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.linling.stitch.crawler.grpc.protobuf.FetchStatus, com.linling.stitch.crawler.grpc.protobuf.FetchStatus.Builder, com.linling.stitch.crawler.grpc.protobuf.FetchStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.linling.stitch.crawler.grpc.protobuf.FetchStatus, com.linling.stitch.crawler.grpc.protobuf.FetchStatus.Builder, com.linling.stitch.crawler.grpc.protobuf.FetchStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private java.lang.Object proxy_ = "";
    /**
     * <code>string proxy = 10;</code>
     */
    public java.lang.String getProxy() {
      java.lang.Object ref = proxy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proxy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proxy = 10;</code>
     */
    public com.google.protobuf.ByteString
        getProxyBytes() {
      java.lang.Object ref = proxy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proxy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proxy = 10;</code>
     */
    public Builder setProxy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proxy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proxy = 10;</code>
     */
    public Builder clearProxy() {
      
      proxy_ = getDefaultInstance().getProxy();
      onChanged();
      return this;
    }
    /**
     * <code>string proxy = 10;</code>
     */
    public Builder setProxyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      proxy_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fetchUrl_ = "";
    /**
     * <code>string fetch_url = 11;</code>
     */
    public java.lang.String getFetchUrl() {
      java.lang.Object ref = fetchUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fetchUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fetch_url = 11;</code>
     */
    public com.google.protobuf.ByteString
        getFetchUrlBytes() {
      java.lang.Object ref = fetchUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fetchUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fetch_url = 11;</code>
     */
    public Builder setFetchUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fetchUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fetch_url = 11;</code>
     */
    public Builder clearFetchUrl() {
      
      fetchUrl_ = getDefaultInstance().getFetchUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string fetch_url = 11;</code>
     */
    public Builder setFetchUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fetchUrl_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crawler.FetchResponse)
  }

  // @@protoc_insertion_point(class_scope:crawler.FetchResponse)
  private static final com.linling.stitch.crawler.grpc.protobuf.FetchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.linling.stitch.crawler.grpc.protobuf.FetchResponse();
  }

  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchResponse>
      PARSER = new com.google.protobuf.AbstractParser<FetchResponse>() {
    @java.lang.Override
    public FetchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.linling.stitch.crawler.grpc.protobuf.FetchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

