// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.grpc.protobuf;

public interface FetchStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crawler.FetchStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.crawler.FetchCode code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.crawler.FetchCode code = 1;</code>
   */
  com.linling.stitch.crawler.grpc.protobuf.FetchCode getCode();

  /**
   * <code>string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
