// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.grpc.protobuf;

public final class FetchProto {
  private FetchProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_Strings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_Strings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchRequest_HeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchRequest_HeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchResponse_HeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchResponse_HeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fetch_FetchResponses_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fetch_FetchResponses_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013fetch.proto\022\005fetch\"\030\n\007Strings\022\r\n\005value" +
      "\030\001 \003(\t\"\324\001\n\014FetchRequest\022\013\n\003url\030\001 \001(\t\022/\n\006" +
      "header\030\004 \003(\0132\037.fetch.FetchRequest.Header" +
      "Entry\022\014\n\004body\030\005 \001(\014\022\016\n\006method\030\006 \001(\t\022\017\n\007t" +
      "imeout\030\007 \001(\003\032=\n\013HeaderEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\035\n\005value\030\002 \001(\0132\016.fetch.Strings:\0028\001J\004\010\002\020" +
      "\003J\004\010\003\020\004R\005proxyR\005proto\":\n\013FetchStatus\022\036\n\004" +
      "code\030\001 \001(\0162\020.fetch.FetchCode\022\013\n\003msg\030\002 \001(" +
      "\t\"\300\002\n\rFetchResponse\022\020\n\010real_url\030\001 \001(\t\022\021\n" +
      "\thttp_code\030\002 \001(\005\022\020\n\010http_msg\030\003 \001(\t\0220\n\006he" +
      "ader\030\004 \003(\0132 .fetch.FetchResponse.HeaderE" +
      "ntry\022\r\n\005proto\030\005 \001(\t\022\014\n\004body\030\006 \001(\014\022\022\n\nfet" +
      "ch_cost\030\007 \001(\003\022\n\n\002ts\030\010 \001(\003\022(\n\014fetch_statu" +
      "s\030\t \001(\0132\022.fetch.FetchStatus\022\r\n\005proxy\030\n \001" +
      "(\t\022\021\n\tfetch_url\030\013 \001(\t\032=\n\013HeaderEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\035\n\005value\030\002 \001(\0132\016.fetch.Strings" +
      ":\0028\001\">\n\016FetchResponses\022,\n\016fetchResponses" +
      "\030\001 \003(\0132\024.fetch.FetchResponse*\345\001\n\tFetchCo" +
      "de\022\r\n\tUNFETCHED\020\000\022\013\n\007FETCHED\020\001\022\021\n\rROBOTS" +
      "_DENIED\020\002\022\021\n\rACCESS_DENIED\020\003\022\017\n\013FETCH_ER" +
      "ROR\020\004\022\022\n\016REDIR_EXCEEDED\020\005\022\021\n\rFETCH_TIMEO" +
      "UT\020\006\022\r\n\tTRUNCATED\020\007\022\022\n\016COMPRESS_ERROR\020\010\022" +
      "\014\n\010IO_ERROR\020\t\022\021\n\rTIMEOUT_ERROR\020\n\022\032\n\026ILLE" +
      "GAL_ARGUMENT_ERROR\020\0132\301\001\n\014FetchService\0224\n" +
      "\005Fetch\022\023.fetch.FetchRequest\032\024.fetch.Fetc" +
      "hResponse\"\000\022<\n\nFetchMulti\022\023.fetch.FetchR" +
      "equest\032\025.fetch.FetchResponses\"\000(\001\022=\n\nAsy" +
      "ncFetch\022\023.fetch.FetchRequest\032\024.fetch.Fet" +
      "chResponse\"\000(\0010\001B+\n\033com.newsbreak.grpc.p" +
      "rotobufB\nFetchProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_fetch_Strings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fetch_Strings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_Strings_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_fetch_FetchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fetch_FetchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchRequest_descriptor,
        new java.lang.String[] { "Url", "Header", "Body", "Method", "Timeout", });
    internal_static_fetch_FetchRequest_HeaderEntry_descriptor =
      internal_static_fetch_FetchRequest_descriptor.getNestedTypes().get(0);
    internal_static_fetch_FetchRequest_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchRequest_HeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_fetch_FetchStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_fetch_FetchStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchStatus_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_fetch_FetchResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_fetch_FetchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchResponse_descriptor,
        new java.lang.String[] { "RealUrl", "HttpCode", "HttpMsg", "Header", "Proto", "Body", "FetchCost", "Ts", "FetchStatus", "Proxy", "FetchUrl", });
    internal_static_fetch_FetchResponse_HeaderEntry_descriptor =
      internal_static_fetch_FetchResponse_descriptor.getNestedTypes().get(0);
    internal_static_fetch_FetchResponse_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchResponse_HeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_fetch_FetchResponses_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_fetch_FetchResponses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fetch_FetchResponses_descriptor,
        new java.lang.String[] { "FetchResponses", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
