// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.grpc.protobuf;

/**
 * Protobuf type {@code crawler.FetchResponses}
 */
public  final class FetchResponses extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crawler.FetchResponses)
    FetchResponsesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchResponses.newBuilder() to construct.
  private FetchResponses(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchResponses() {
    fetchResponses_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FetchResponses(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              fetchResponses_ = new java.util.ArrayList<com.linling.stitch.crawler.grpc.protobuf.FetchResponse>();
              mutable_bitField0_ |= 0x00000001;
            }
            fetchResponses_.add(
                input.readMessage(com.linling.stitch.crawler.grpc.protobuf.FetchResponse.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        fetchResponses_ = java.util.Collections.unmodifiableList(fetchResponses_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponses_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponses_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.linling.stitch.crawler.grpc.protobuf.FetchResponses.class, com.linling.stitch.crawler.grpc.protobuf.FetchResponses.Builder.class);
  }

  public static final int FETCHRESPONSES_FIELD_NUMBER = 1;
  private java.util.List<com.linling.stitch.crawler.grpc.protobuf.FetchResponse> fetchResponses_;
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  public java.util.List<com.linling.stitch.crawler.grpc.protobuf.FetchResponse> getFetchResponsesList() {
    return fetchResponses_;
  }
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  public java.util.List<? extends com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder> 
      getFetchResponsesOrBuilderList() {
    return fetchResponses_;
  }
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  public int getFetchResponsesCount() {
    return fetchResponses_.size();
  }
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  public com.linling.stitch.crawler.grpc.protobuf.FetchResponse getFetchResponses(int index) {
    return fetchResponses_.get(index);
  }
  /**
   * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
   */
  public com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder getFetchResponsesOrBuilder(
      int index) {
    return fetchResponses_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fetchResponses_.size(); i++) {
      output.writeMessage(1, fetchResponses_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < fetchResponses_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, fetchResponses_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.linling.stitch.crawler.grpc.protobuf.FetchResponses)) {
      return super.equals(obj);
    }
    com.linling.stitch.crawler.grpc.protobuf.FetchResponses other = (com.linling.stitch.crawler.grpc.protobuf.FetchResponses) obj;

    if (!getFetchResponsesList()
        .equals(other.getFetchResponsesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFetchResponsesCount() > 0) {
      hash = (37 * hash) + FETCHRESPONSES_FIELD_NUMBER;
      hash = (53 * hash) + getFetchResponsesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.linling.stitch.crawler.grpc.protobuf.FetchResponses prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crawler.FetchResponses}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crawler.FetchResponses)
      com.linling.stitch.crawler.grpc.protobuf.FetchResponsesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponses_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linling.stitch.crawler.grpc.protobuf.FetchResponses.class, com.linling.stitch.crawler.grpc.protobuf.FetchResponses.Builder.class);
    }

    // Construct using com.linling.stitch.crawler.grpc.protobuf.FetchResponses.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFetchResponsesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (fetchResponsesBuilder_ == null) {
        fetchResponses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        fetchResponsesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.linling.stitch.crawler.grpc.protobuf.CrawlerProto.internal_static_crawler_FetchResponses_descriptor;
    }

    @java.lang.Override
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponses getDefaultInstanceForType() {
      return com.linling.stitch.crawler.grpc.protobuf.FetchResponses.getDefaultInstance();
    }

    @java.lang.Override
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponses build() {
      com.linling.stitch.crawler.grpc.protobuf.FetchResponses result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponses buildPartial() {
      com.linling.stitch.crawler.grpc.protobuf.FetchResponses result = new com.linling.stitch.crawler.grpc.protobuf.FetchResponses(this);
      int from_bitField0_ = bitField0_;
      if (fetchResponsesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fetchResponses_ = java.util.Collections.unmodifiableList(fetchResponses_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fetchResponses_ = fetchResponses_;
      } else {
        result.fetchResponses_ = fetchResponsesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.linling.stitch.crawler.grpc.protobuf.FetchResponses) {
        return mergeFrom((com.linling.stitch.crawler.grpc.protobuf.FetchResponses)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.linling.stitch.crawler.grpc.protobuf.FetchResponses other) {
      if (other == com.linling.stitch.crawler.grpc.protobuf.FetchResponses.getDefaultInstance()) return this;
      if (fetchResponsesBuilder_ == null) {
        if (!other.fetchResponses_.isEmpty()) {
          if (fetchResponses_.isEmpty()) {
            fetchResponses_ = other.fetchResponses_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFetchResponsesIsMutable();
            fetchResponses_.addAll(other.fetchResponses_);
          }
          onChanged();
        }
      } else {
        if (!other.fetchResponses_.isEmpty()) {
          if (fetchResponsesBuilder_.isEmpty()) {
            fetchResponsesBuilder_.dispose();
            fetchResponsesBuilder_ = null;
            fetchResponses_ = other.fetchResponses_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fetchResponsesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFetchResponsesFieldBuilder() : null;
          } else {
            fetchResponsesBuilder_.addAllMessages(other.fetchResponses_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.linling.stitch.crawler.grpc.protobuf.FetchResponses parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.linling.stitch.crawler.grpc.protobuf.FetchResponses) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.linling.stitch.crawler.grpc.protobuf.FetchResponse> fetchResponses_ =
      java.util.Collections.emptyList();
    private void ensureFetchResponsesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fetchResponses_ = new java.util.ArrayList<com.linling.stitch.crawler.grpc.protobuf.FetchResponse>(fetchResponses_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.linling.stitch.crawler.grpc.protobuf.FetchResponse, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder, com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder> fetchResponsesBuilder_;

    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public java.util.List<com.linling.stitch.crawler.grpc.protobuf.FetchResponse> getFetchResponsesList() {
      if (fetchResponsesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fetchResponses_);
      } else {
        return fetchResponsesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public int getFetchResponsesCount() {
      if (fetchResponsesBuilder_ == null) {
        return fetchResponses_.size();
      } else {
        return fetchResponsesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponse getFetchResponses(int index) {
      if (fetchResponsesBuilder_ == null) {
        return fetchResponses_.get(index);
      } else {
        return fetchResponsesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder setFetchResponses(
        int index, com.linling.stitch.crawler.grpc.protobuf.FetchResponse value) {
      if (fetchResponsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFetchResponsesIsMutable();
        fetchResponses_.set(index, value);
        onChanged();
      } else {
        fetchResponsesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder setFetchResponses(
        int index, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder builderForValue) {
      if (fetchResponsesBuilder_ == null) {
        ensureFetchResponsesIsMutable();
        fetchResponses_.set(index, builderForValue.build());
        onChanged();
      } else {
        fetchResponsesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder addFetchResponses(com.linling.stitch.crawler.grpc.protobuf.FetchResponse value) {
      if (fetchResponsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFetchResponsesIsMutable();
        fetchResponses_.add(value);
        onChanged();
      } else {
        fetchResponsesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder addFetchResponses(
        int index, com.linling.stitch.crawler.grpc.protobuf.FetchResponse value) {
      if (fetchResponsesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFetchResponsesIsMutable();
        fetchResponses_.add(index, value);
        onChanged();
      } else {
        fetchResponsesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder addFetchResponses(
        com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder builderForValue) {
      if (fetchResponsesBuilder_ == null) {
        ensureFetchResponsesIsMutable();
        fetchResponses_.add(builderForValue.build());
        onChanged();
      } else {
        fetchResponsesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder addFetchResponses(
        int index, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder builderForValue) {
      if (fetchResponsesBuilder_ == null) {
        ensureFetchResponsesIsMutable();
        fetchResponses_.add(index, builderForValue.build());
        onChanged();
      } else {
        fetchResponsesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder addAllFetchResponses(
        java.lang.Iterable<? extends com.linling.stitch.crawler.grpc.protobuf.FetchResponse> values) {
      if (fetchResponsesBuilder_ == null) {
        ensureFetchResponsesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fetchResponses_);
        onChanged();
      } else {
        fetchResponsesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder clearFetchResponses() {
      if (fetchResponsesBuilder_ == null) {
        fetchResponses_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fetchResponsesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public Builder removeFetchResponses(int index) {
      if (fetchResponsesBuilder_ == null) {
        ensureFetchResponsesIsMutable();
        fetchResponses_.remove(index);
        onChanged();
      } else {
        fetchResponsesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder getFetchResponsesBuilder(
        int index) {
      return getFetchResponsesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder getFetchResponsesOrBuilder(
        int index) {
      if (fetchResponsesBuilder_ == null) {
        return fetchResponses_.get(index);  } else {
        return fetchResponsesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public java.util.List<? extends com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder> 
         getFetchResponsesOrBuilderList() {
      if (fetchResponsesBuilder_ != null) {
        return fetchResponsesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fetchResponses_);
      }
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder addFetchResponsesBuilder() {
      return getFetchResponsesFieldBuilder().addBuilder(
          com.linling.stitch.crawler.grpc.protobuf.FetchResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder addFetchResponsesBuilder(
        int index) {
      return getFetchResponsesFieldBuilder().addBuilder(
          index, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .crawler.FetchResponse fetchResponses = 1;</code>
     */
    public java.util.List<com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder> 
         getFetchResponsesBuilderList() {
      return getFetchResponsesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.linling.stitch.crawler.grpc.protobuf.FetchResponse, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder, com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder> 
        getFetchResponsesFieldBuilder() {
      if (fetchResponsesBuilder_ == null) {
        fetchResponsesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.linling.stitch.crawler.grpc.protobuf.FetchResponse, com.linling.stitch.crawler.grpc.protobuf.FetchResponse.Builder, com.linling.stitch.crawler.grpc.protobuf.FetchResponseOrBuilder>(
                fetchResponses_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        fetchResponses_ = null;
      }
      return fetchResponsesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crawler.FetchResponses)
  }

  // @@protoc_insertion_point(class_scope:crawler.FetchResponses)
  private static final com.linling.stitch.crawler.grpc.protobuf.FetchResponses DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.linling.stitch.crawler.grpc.protobuf.FetchResponses();
  }

  public static com.linling.stitch.crawler.grpc.protobuf.FetchResponses getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchResponses>
      PARSER = new com.google.protobuf.AbstractParser<FetchResponses>() {
    @java.lang.Override
    public FetchResponses parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchResponses(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchResponses> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchResponses> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.linling.stitch.crawler.grpc.protobuf.FetchResponses getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

