// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fetch.proto

package com.linling.stitch.crawler.grpc.protobuf;

public interface FetchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crawler.FetchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string proxy = 2;</code>
   */
  java.lang.String getProxy();
  /**
   * <code>string proxy = 2;</code>
   */
  com.google.protobuf.ByteString
      getProxyBytes();

  /**
   * <code>map&lt;string, string&gt; header = 3;</code>
   */
  int getHeaderCount();
  /**
   * <code>map&lt;string, string&gt; header = 3;</code>
   */
  boolean containsHeader(
      java.lang.String key);
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getHeader();
  /**
   * <code>map&lt;string, string&gt; header = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getHeaderMap();
  /**
   * <code>map&lt;string, string&gt; header = 3;</code>
   */

  java.lang.String getHeaderOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; header = 3;</code>
   */

  java.lang.String getHeaderOrThrow(
      java.lang.String key);

  /**
   * <code>bytes body = 4;</code>
   */
  com.google.protobuf.ByteString getBody();

  /**
   * <code>string method = 5;</code>
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 5;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>int64 timeout = 6;</code>
   */
  long getTimeout();
}
